#! /bin/bash
rm -rf /etc/$TURBO_PARAKEET_DEFAULT_NAME;
rm -rf /opt/$TURBO_PARAKEET_DEFAULT_NAME;
rm -rf /var/log/$TURBO_PARAKEET_DEFAULT_NAME;
mkdir /etc/$TURBO_PARAKEET_DEFAULT_NAME;
ssh-keygen -t rsa -b 4096 -N "" -C "$TURBO_PARAKEET_EMAIL" -f ./static/$TURBO_PARAKEET_DEFAULT_NAME;
cp ./static/configs.json /etc/$TURBO_PARAKEET_DEFAULT_NAME/;
mkdir /opt/$TURBO_PARAKEET_DEFAULT_NAME;
mkdir /opt/$TURBO_PARAKEET_DEFAULT_NAME/.key;
cp -r ./bin /opt/$TURBO_PARAKEET_DEFAULT_NAME;
cp ./static/$TURBO_PARAKEET_DEFAULT_NAME /opt/$TURBO_PARAKEET_DEFAULT_NAME/.key;
chown $USER:$USER /opt/$TURBO_PARAKEET_DEFAULT_NAME/.key/$TURBO_PARAKEET_DEFAULT_NAME;
touch /var/log/$TURBO_PARAKEET_DEFAULT_NAME;
chown $USER:$USER /var/log/$TURBO_PARAKEET_DEFAULT_NAME;
chmod 0755 /var/log/$TURBO_PARAKEET_DEFAULT_NAME;